### PR TITLE
remove thermokarst as maintainer

### PR DESCRIPTION
**Pull request by thermokarst**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thermokarst** [comment]
@conda-forge-admin, please rerender

**Comment by ElDeveloper** [comment]
@conda-forge-admin please rerender

**Comment by ElDeveloper** [comment]
@ebolyen looks like there's a few test failures:

```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED alignment/tests/test_tabular_msa.py::TestLoc::test_multiindex_complicated_axis - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.
FAILED alignment/tests/test_tabular_msa.py::TestLoc::test_multiindex_complicated_axis_empty_selection - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.
FAILED sequence/tests/test_sequence.py::TestSequence::test_init_invalid_sequence - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.
FAILED sequence/tests/test_sequence.py::TestSequence::test_munge_to_index_array_valid_iterable - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10,) + inhomogeneous part.
========== 4 failed, 2572 passed, 30 skipped, 130 warnings in 46.83s ===========
Tests failed for scikit-bio-0.5.8-py38h07e1bb6_2.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for scikit-bio-0.5.8-py38h07e1bb6_2.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: scikit-bio-0.5.8-py38h07e1bb6_2.conda
```

Any ideas on how we might fix this here?

**Comment by thermokarst** [comment]
@conda-forge-admin please rerender

**Pull request closed without merging**
