### PR TITLE
Adds Qiyun as a maintainer

### PR DESCRIPTION
**Pull request by ebolyen**
Part of the scikit-bio revitalization:
https://github.com/scikit-bio/scikit-bio/discussions/1935

### CODE REVIEW

**Comment by ebolyen** [comment]
@conda-forge-admin please rerender

**Comment by wasade** [comment]
@ebolyen, since your kicking this, could you remove @thermokarst as well?

**Comment by ebolyen** [comment]
@wasade, yep!

**Comment by wasade** [comment]
Thanks!

**Comment by ebolyen** [comment]
@conda-forge-admin please rerender

**Pull request merged**
